services:
  postfix:
    container_name: postfix
    hostname: postfix
    build:
      context: .
    ports:
      - "25:25"
      - "465:465"
      - "2525:2525"
      - "2526:2526"

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    hostname: mailpit
    ports:
      - "8025:8025"

  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher
    hostname: mailcatcher
    ports:
      - "8080:1080"